apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-pipeline
  name: argocd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-pipeline
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-pipeline
    spec:
      containers:
      - name: argocd-pipeline
        image: vishalbodkhe532/argocd-pipeline:080975eb1a16cd4a0b2344664ea18ba2a4d2086c
        resources: {}
status: {}
