apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-pipeline
  name: argocd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-pipeline
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-pipeline
    spec:
      containers:
      - name: argocd-pipeline
        image: vishalbodkhe532/argocd-pipeline:1f9a638759c903995cb280526a0b98288fbe3ecc
        resources: {}
status: {}
