apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-pipeline
  name: argocd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-pipeline
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-pipeline
    spec:
      containers:
      - name: argocd-pipeline
        image: vishalbodkhe532/argocd-pipeline:9f612b0d7f70a7b31145aa1e7551e4b097ae39e3
        resources: {}
status: {}
